apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapptodo
  labels:
    app: myapptodo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/api/todo"
spec:
  rules:
    - host: YOURINGRESSIP.xip.io
      http:
        paths:
          - path: /api/todo
            backend:
              serviceName: myapptodo
              servicePort: 8080
